target 'pjsip-ios', :exclusive => true do
  pod "pjsip-ios", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "pjsip-ios", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
